name                     = "example-storage-account"
location                 = "eastus2"
account_tier             = "Standard"
account_replication_type = "LRS"
account_kind             = "StorageV2"
rg_name                  = "SarlesResourceGroup"
subscription_id          = "d003ea48-de34-4898-8ad4-daa31fd6479c"
