name: Terraform Plan

on:
  workflow_dispatch

jobs:
  call-reusable-workflow:
    uses: rsarles/terraform-cicd-pipeline/.github/workflows/terraform-plan.yml@main
    with: 
      terraform_version: '1.10'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      CICD_PAT: ${{ secrets.CICD_PAT }}