name: Terraform Plan

# on:
#   push:
#     branches:
#       - main
on:
  workflow_dispatch

jobs:
  call-reusable-workflow:
    uses: rsarles/terraform-cicd-pipeline/.github/workflows/terraform-plan.yml@main
    with: 
      terraform_version: '1.10'
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}